const db = [
  { title: '말을잇지못하는', subtitle: '케장콘 1', arg: '1' },
  { title: '크흑 감사합니다 SENSEI', subtitle: '케장콘 1', arg: '1' },
  { title: '그러셨군요 가족분들도 알고 계신가요', subtitle: '케장콘 1', arg: '1' },
  { title: '틀린말 안혔다잉 ㅅㄱ', subtitle: '케장콘 1', arg: '1' },
  { title: '그럼 하지말자', subtitle: '케장콘 1', arg: '1' },
  { title: '어쨌든 제 탓은 아닌듯함', subtitle: '케장콘 1', arg: '1' },
  { title: '예 축하드리고요', subtitle: '케장콘 1', arg: '1' },
  { title: '저언하아아 아무도 여쭙지 않았사옵니다', subtitle: '케장콘 1', arg: '1' },
  { title: '당근빳다죠 쉬바', subtitle: '케장콘 1', arg: '1' },
  { title: '오홍홍 조와용', subtitle: '케장콘 1', arg: '1' },
  { title: '앗 아아', subtitle: '케장콘 1', arg: '1' },
  { title: '대신귀여운알파카를드리겟습니다', subtitle: '케장콘 1', arg: '1' },
  { title: '어쩌라고', subtitle: '케장콘 1', arg: '1' },
  { title: '머임', subtitle: '케장콘 1', arg: '1' },
  { title: '그건 또 뭔 야 너 문과지', subtitle: '케장콘 1', arg: '1' },
  { title: '워메 오져따잉', subtitle: '케장콘 1', arg: '1' },
  { title: '넹 기분굿', subtitle: '케장콘 1', arg: '1' },
  { title: '머쓱', subtitle: '케장콘 1', arg: '1' },
  { title: '허미', subtitle: '케장콘 1', arg: '1' },
  { title: '내', subtitle: '케장콘 1', arg: '1' },
  { title: '띠요오오오오오오 오오오옹ㅇㅇㅇㅇㅇ (띠용)', subtitle: '케장콘 1', arg: '1' },
  { title: '끼요오오옷ㅅㅅ', subtitle: '케장콘 1', arg: '1' },
  { title: '아 너무 무섭다', subtitle: '케장콘 1', arg: '1' },
  { title: '잘 몰르겠고 ㅎ ㅎㅎ', subtitle: '케장콘 1', arg: '1' },
  { title: '그걸 믿었음 째트킥', subtitle: '케장콘 2', arg: '2' },
  { title: '호다다다닥', subtitle: '케장콘 2', arg: '2' },
  { title: '나는 이 대화 자체를 못 따라가겠어', subtitle: '케장콘 2', arg: '2' },
  { title: '실화아닐걸 맞아 역시 실화일리가 없지', subtitle: '케장콘 2', arg: '2' },
  { title: '으흐어어어어엉 으으윽 흑흑', subtitle: '케장콘 2', arg: '2' },
  { title: '그런 유익한걸 감상할 시간따윈 없어', subtitle: '케장콘 2', arg: '2' },
  { title: '이게 말이야 기린이야', subtitle: '케장콘 2', arg: '2' },
  { title: 'ㅋㅋㅋㅋ좋다 지금간다 기다려라', subtitle: '케장콘 2', arg: '2' },
  { title: '생각해보니까 진짜 그러네', subtitle: '케장콘 2', arg: '2' },
  { title: '아 싫어요 가요 쫌', subtitle: '케장콘 2', arg: '2' },
  { title: '아 안사요', subtitle: '케장콘 2', arg: '2' },
  { title: '있었는데요', subtitle: '케장콘 2', arg: '2' },
  { title: '없었습니다', subtitle: '케장콘 2', arg: '2' },
  { title: '저바 또또또또ㄸ또또 한마디를 안질려고 아주', subtitle: '케장콘 2', arg: '2' },
  { title: '엥 알고잇섯다구예', subtitle: '케장콘 2', arg: '2' },
  { title: '두뇌 3000 가동중', subtitle: '케장콘 2', arg: '2' },
  { title: '와 정말 알고싶던 내용이었어요 감사합니다', subtitle: '케장콘 2', arg: '2' },
  { title: '으따 마 행님요 이거 상이라도 드려야 쓰겠구마', subtitle: '케장콘 2', arg: '2' },
  { title: '짜식이말여 잘못해서 않해서 어', subtitle: '케장콘 2', arg: '2' },
  { title: '음 들을 가치가 있는 내용이었다', subtitle: '케장콘 2', arg: '2' },
  { title: '저건 진짜 사람이 아니다 사이버 망령이지', subtitle: '케장콘 2', arg: '2' },
  { title: '(놀라는 표정 있는거 후광처럼 생긴 그거)', subtitle: '케장콘 2', arg: '2' },
  { title: '크 고건 몰랏내', subtitle: '케장콘 2', arg: '2' },
  { title: '모레는거냐', subtitle: '케장콘 2', arg: '2' },
  { title: '별님달님 제발 인생을 날로먹을수 잇개 해주세요', subtitle: '케장콘 3', arg: '3' },
  { title: '않갈켜줌 ㅅㄱ 니가아쉽지 내가아쉽냐?', subtitle: '케장콘 3', arg: '3' },
  { title: '어멋 넘 귀엽다', subtitle: '케장콘 3', arg: '3' },
  { title: '와우 이거 실제이야기를 바탕으로 두고있냐 a.k.a. 실화냐', subtitle: '케장콘 3', arg: '3' },
  { title: '어흑 마이깟', subtitle: '케장콘 3', arg: '3' },
  { title: '핫하 받아라', subtitle: '케장콘 3', arg: '3' },
  { title: '빨리빨리 빨리', subtitle: '케장콘 3', arg: '3' },
  { title: '뭐요', subtitle: '케장콘 3', arg: '3' },
  { title: '그거 참 겁나게 살벌한 상상이구마', subtitle: '케장콘 3', arg: '3' },
  { title: '예 아니라구예', subtitle: '케장콘 3', arg: '3' },
  { title: '모야저개 정신놧나바', subtitle: '케장콘 3', arg: '3' },
  { title: '뭐라는거야', subtitle: '케장콘 3', arg: '3' },
  { title: '슛', subtitle: '케장콘 3', arg: '3' },
  { title: '니가 그렇다면 그런거겠지 니 상상 속에서만 말이야', subtitle: '케장콘 3', arg: '3' },
  { title: '하이고 의미없다', subtitle: '케장콘 3', arg: '3' },
  { title: '그 그렇군요', subtitle: '케장콘 3', arg: '3' },
  { title: '저도 가끔씩 그 사실을 깨닫고 놀라곤 한답니다', subtitle: '케장콘 3', arg: '3' },
  { title: 'ㅎㅎ 저에 어둠 인격에 그만', subtitle: '케장콘 3', arg: '3' },
  { title: '와 오졋다', subtitle: '케장콘 3', arg: '3' },
  { title: '진짜다 진짜', subtitle: '케장콘 3', arg: '3' },
  { title: '그런가 그런가 그런가 그런가', subtitle: '케장콘 3', arg: '3' },
  { title: '????????????????(물음표 많은거)', subtitle: '케장콘 3', arg: '3' },
  { title: '아니 진심', subtitle: '케장콘 3', arg: '3' },
  { title: '맞아요 누가 아니래요', subtitle: '케장콘 3', arg: '3' },
  { title: '와우 리을리', subtitle: '케장콘 4', arg: '4' },
  { title: '아니 이놈애 머 아는개 업내', subtitle: '케장콘 4', arg: '4' },
  { title: '짜슥이 야 맛고쉽냐', subtitle: '케장콘 4', arg: '4' },
  { title: '예아 베이비', subtitle: '케장콘 4', arg: '4' },
  { title: '고오얀놈', subtitle: '케장콘 4', arg: '4' },
  { title: '아니 억떡계 이럴수가 잇어', subtitle: '케장콘 4', arg: '4' },
  { title: '에에엥', subtitle: '케장콘 4', arg: '4' },
  { title: '응 아니야', subtitle: '케장콘 4', arg: '4' },
  { title: '에이 1절만 하세요', subtitle: '케장콘 4', arg: '4' },
  { title: '아이고 잘했다 우리 모질이', subtitle: '케장콘 4', arg: '4' },
  { title: 'ㄳ ㅎㅎ', subtitle: '케장콘 4', arg: '4' },
  { title: '크흑 귀여워', subtitle: '케장콘 4', arg: '4' },
  { title: '응 10점 만점에 3점 정도', subtitle: '케장콘 4', arg: '4' },
  { title: '와우 무슨일이 일어나고 잇는것이지', subtitle: '케장콘 4', arg: '4' },
  { title: '잘몰르겟음 몬가 몬가 일어나고 잇음', subtitle: '케장콘 4', arg: '4' },
  { title: 'ㅎㅎ는 흑흑입니다만', subtitle: '케장콘 4', arg: '4' },
  { title: '으겍 퉷퉷퉷', subtitle: '케장콘 4', arg: '4' },
  { title: '참나 그걸 아니 이게 와 진심', subtitle: '케장콘 4', arg: '4' },
  { title: '정말 뼈가되고 뼈가되는 교육이다', subtitle: '케장콘 4', arg: '4' },
  { title: '알게 뭐람 호호', subtitle: '케장콘 4', arg: '4' },
  { title: '으으음 흠 흐으으으으으으으으으으음', subtitle: '케장콘 4', arg: '4' },
  { title: '않되', subtitle: '케장콘 4', arg: '4' },
  { title: '나에 말이 맛는거 갓은디', subtitle: '케장콘 4', arg: '4' },
  { title: '기대 설렘', subtitle: '케장콘 4', arg: '4' },
  { title: '감동 (눈물)', subtitle: '케장콘 5', arg: '5' },
  { title: '음', subtitle: '케장콘 5', arg: '5' },
  { title: '당신 뭘 믿고 이런 짓 하는거야', subtitle: '케장콘 5', arg: '5' },
  { title: '야 이만큼 실패했으면 성공할 때 됐다', subtitle: '케장콘 5', arg: '5' },
  { title: '하아니 이게 왜 안되지', subtitle: '케장콘 5', arg: '5' },
  { title: '(몸에서 빨간 전기같은거 나가는거)', subtitle: '케장콘 5', arg: '5' },
  { title: '이게 대체 뭐지 이것 보세요 윽 역겨워', subtitle: '케장콘 5', arg: '5' },
  { title: '그런 방법은 없습니다', subtitle: '케장콘 5', arg: '5' },
  { title: '모샘 즐이샘 잼업으샘 않할꺼샘', subtitle: '케장콘 5', arg: '5' },
  { title: '으악 멈춰 스플뎀무엇', subtitle: '케장콘 5', arg: '5' },
  { title: '과학적', subtitle: '케장콘 5', arg: '5' },
  { title: '정말 구구절절 헛소리만 하는군', subtitle: '케장콘 5', arg: '5' },
  { title: '저도 잘 몰르는데요 몰름보 반장', subtitle: '케장콘 5', arg: '5' },
  { title: '와 나까지 긴장된다', subtitle: '케장콘 5', arg: '5' },
  { title: '???(물음표3개 흔들리는거)', subtitle: '케장콘 5', arg: '5' },
  { title: '무순말을 그럭게하세요 (뮤순말)', subtitle: '케장콘 5', arg: '5' },
  { title: '좋아 밥탐이군', subtitle: '케장콘 5', arg: '5' },
  { title: '걍해봄', subtitle: '케장콘 5', arg: '5' },
  { title: '까짓거 그럽시다', subtitle: '케장콘 5', arg: '5' },
  { title: '불꽃가능 할뚜이따', subtitle: '케장콘 5', arg: '5' },
  { title: '시민들도 고통을 호소하고 있습니다', subtitle: '케장콘 5', arg: '5' },
  { title: '이미 본거야', subtitle: '케장콘 5', arg: '5' },
  { title: '이거 인권침혜 아니냐', subtitle: '케장콘 5', arg: '5' },
  { title: '하지만사랑만있으면괜찮지않을까', subtitle: '케장콘 5', arg: '5' },
  { title: '정신차려', subtitle: '케장콘 6', arg: '6' },
  { title: '마 니 자신잇나 니 자신 늠치나 니 자신 에 주채가 않 대나', subtitle: '케장콘 6', arg: '6' },
  { title: '헐', subtitle: '케장콘 6', arg: '6' },
  { title: '어째서 그렇게 생각하시지', subtitle: '케장콘 6', arg: '6' },
  { title: '저를말씀 하신 거라면 브라질땅콩 입니다 난 브라질땅콩 이 다', subtitle: '케장콘 6', arg: '6' },
  { title: '시간을 가치있게 쓰는 사람이 있다면 헛되이 쓰는 사람도 있어야해 그래야 우주의 균형이 맞을것 아냐', subtitle: '케장콘 6', arg: '6'
  },
  { title: '암말도않했는뎁쇼', subtitle: '케장콘 6', arg: '6' },
  { title: '모라고요', subtitle: '케장콘 6', arg: '6' },
  { title: '휴지통 (들어가면못나옴)', subtitle: '케장콘 6', arg: '6' },
  { title: '하하 싫어', subtitle: '케장콘 6', arg: '6' },
  { title: '머여', subtitle: '케장콘 6', arg: '6' },
  { title: '이번에는 정말 잘할수 잇을꺼 야', subtitle: '케장콘 6', arg: '6' },
  { title: '흠 흠미', subtitle: '케장콘 6', arg: '6' },
  { title: '안녕하세요', subtitle: '케장콘 6', arg: '6' },
  { title: '다음날', subtitle: '케장콘 6', arg: '6' },
  { title: '도당채 왜 그러한 짓을', subtitle: '케장콘 6', arg: '6' },
  { title: '너 그런거 보니', subtitle: '케장콘 6', arg: '6' },
  { title: '(떨리다 눈 떨어지는거)', subtitle: '케장콘 6', arg: '6' },
  { title: '게헥', subtitle: '케장콘 6', arg: '6' },
  { title: '감사합니다', subtitle: '케장콘 6', arg: '6' },
  { title: '아 아닌데요', subtitle: '케장콘 6', arg: '6' },
  { title: '않하면않됨', subtitle: '케장콘 6', arg: '6' },
  { title: '뭐야 돌려줘요', subtitle: '케장콘 6', arg: '6' },
  { title: '와 진짜 용하다', subtitle: '케장콘 6', arg: '6' },
  { title: '으아 가지말고 내 얘기를 들어', subtitle: '케장콘 7', arg: '7' },
  { title: '이래도 하시겠습니까', subtitle: '케장콘 7', arg: '7' },
  { title: '맨탈에 관리 하여야 한다', subtitle: '케장콘 7', arg: '7' },
  { title: '이것스샷찎었습니다 신고감이다', subtitle: '케장콘 7', arg: '7' },
  { title: '넘 넘졸려 데박 죽는다', subtitle: '케장콘 7', arg: '7' },
  { title: '잘 아셨지요', subtitle: '케장콘 7', arg: '7' },
  { title: '감동 (무표정)', subtitle: '케장콘 7', arg: '7' },
  { title: '나도 아니다', subtitle: '케장콘 7', arg: '7' },
  { title: '그하하학 하학학 하하학 그하학 그하하하 그하학 흐학학', subtitle: '케장콘 7', arg: '7' },
  { title: '축하합니다 당신의 지갑은(는) 사라졌다', subtitle: '케장콘 7', arg: '7' },
  { title: '그래서 제 점수는요 12점 만점에 판문점 입니다', subtitle: '케장콘 7', arg: '7' },
  { title: '아 세상 참 흉흉하여라', subtitle: '케장콘 7', arg: '7' },
  { title: '(책상/밥상 뒤엎는거)', subtitle: '케장콘 7', arg: '7' },
  { title: '이게 이게대체 모슨 소리여', subtitle: '케장콘 7', arg: '7' },
  { title: '왜요', subtitle: '케장콘 7', arg: '7' },
  { title: '내맘아뇨', subtitle: '케장콘 7', arg: '7' },
  { title: '우 야스', subtitle: '케장콘 7', arg: '7' },
  { title: '으아악 아니야', subtitle: '케장콘 7', arg: '7' },
  { title: '하여튼 알지도 못하면서', subtitle: '케장콘 7', arg: '7' },
  { title: '아흐 됐어 말귈을 모알아들어', subtitle: '케장콘 7', arg: '7' },
  { title: '예', subtitle: '케장콘 7', arg: '7' },
  { title: '저용', subtitle: '케장콘 7', arg: '7' },
  { title: '한심', subtitle: '케장콘 7', arg: '7' },
  { title: '사실은 그릇개 생강안혀', subtitle: '케장콘 7', arg: '7' },
  { title: '오늘부터 우리 베프인 부분인 각이다', subtitle: '케장콘 8', arg: '8' },
  { title: '으음 분하지만 맞는 말이다 하지만 분하다', subtitle: '케장콘 8', arg: '8' },
  { title: '(핸드폰 받아들고 놀라면서 느낌표 !!!!! 뜨는거)', subtitle: '케장콘 8', arg: '8' },
  { title: '오지는부분 인정하는각 1따봉 드렸구요', subtitle: '케장콘 8', arg: '8' },
  { title: '근데 누구시죠', subtitle: '케장콘 8', arg: '8' },
  { title: '그럴까요', subtitle: '케장콘 8', arg: '8' },
  { title: '아랫분도 이미 동의하신 부분 ㄹㅇ', subtitle: '케장콘 8', arg: '8' },
  { title: '흑흑 난 단지 도와주고 싶었을 뿐인데', subtitle: '케장콘 8', arg: '8' },
  { title: '싫어', subtitle: '케장콘 8', arg: '8' },
  { title: '힝잉', subtitle: '케장콘 8', arg: '8' },
  { title: '싸우지 말고 친목해', subtitle: '케장콘 8', arg: '8' },
  { title: '모냐는', subtitle: '케장콘 8', arg: '8' },
  { title: '저런 쯧쯧', subtitle: '케장콘 8', arg: '8' },
  { title: '생각풍선과 ? 나오는거', subtitle: '케장콘 8', arg: '8' },
  { title: '아잇 진정해', subtitle: '케장콘 8', arg: '8' },
  { title: '어른들은 아무것도 몰라', subtitle: '케장콘 8', arg: '8' },
  { title: '예 엉님', subtitle: '케장콘 8', arg: '8' },
  { title: '하트 반짝이는거', subtitle: '케장콘 8', arg: '8' },
  { title: '아 예', subtitle: '케장콘 8', arg: '8' },
  { title: '라고 할줄을 아셧습니까', subtitle: '케장콘 8', arg: '8' },
  { title: '오들오들', subtitle: '케장콘 8', arg: '8' },
  { title: '파워풀 홀스(말세다)', subtitle: '케장콘 8', arg: '8' },
  { title: '이거 더갖고와 아니지 더갖고와가 아니야 다갖고와', subtitle: '케장콘 8', arg: '8' },
  { title: 'ㅎㅎㅎㅎㅎㅎ', subtitle: '케장콘 8', arg: '8' },
  { title: '지금 공부하면 꿈을 이루지만', subtitle: '케장콘 9', arg: '9' },
  { title: '지금 자면 잠을 이룬다 잠 은 이루어진다', subtitle: '케장콘 9', arg: '9' },
  { title: '퍼스널 윈드 (개인적인 바람)', subtitle: '케장콘 9', arg: '9' },
  { title: '아니 매너하라고', subtitle: '케장콘 9', arg: '9' },
  { title: '그게다야 뭘더바래', subtitle: '케장콘 9', arg: '9' },
  { title: '몰바라냐고 그게다라고 아악 그게다라고', subtitle: '케장콘 9', arg: '9' },
  { title: '집가고싶어', subtitle: '케장콘 9', arg: '9' },
  { title: '이런걸로 경쟁좀 하지마', subtitle: '케장콘 9', arg: '9' },
  { title: '머임', subtitle: '케장콘 9', arg: '9' },
  { title: 'Right now (여기서 우회전)', subtitle: '케장콘 9', arg: '9' },
  { title: '팝콘 좋아', subtitle: '케장콘 9', arg: '9' },
  { title: '짜식이 짜게먹으면 안좋다', subtitle: '케장콘 9', arg: '9' },
  { title: '급침환', subtitle: '케장콘 9', arg: '9' },
  { title: '진상도 정돈컷', subtitle: '케장콘 9', arg: '9' },
  { title: '따라서 유죄입니다', subtitle: '케장콘 9', arg: '9' },
  { title: '나다', subtitle: '케장콘 9', arg: '9' },
  { title: '크ㅓ크크큭', subtitle: '케장콘 9', arg: '9' },
  { title: '어떴 억떻에 었떳에 그럴수가', subtitle: '케장콘 9', arg: '9' },
  { title: '모삿어요', subtitle: '케장콘 9', arg: '9' },
  { title: '충동구매라 영수증 봐야 앎', subtitle: '케장콘 9', arg: '9' },
  { title: '어떻게알아요', subtitle: '케장콘 9', arg: '9' },
  { title: '아니오', subtitle: '케장콘 9', arg: '9' },
  { title: '아주 못됐어', subtitle: '케장콘 9', arg: '9' },
  { title: '이게 현실인거예요', subtitle: '케장콘 9', arg: '9' },
  { title: '와아 와아아아아 일찍 일어난 보람 有', subtitle: '케장콘 10', arg: '10' },
  { title: '여보시어요', subtitle: '케장콘 10', arg: '10' },
  { title: '그렇게까지 물어보시면 할 말은 없구요', subtitle: '케장콘 10', arg: '10' },
  { title: '흠 글쎄요', subtitle: '케장콘 10', arg: '10' },
  { title: '나도 한입만', subtitle: '케장콘 10', arg: '10' },
  { title: '뻥이야', subtitle: '케장콘 10', arg: '10' },
  { title: '(좌우로 오두방정떠는거)', subtitle: '케장콘 10', arg: '10' },
  { title: '응너도', subtitle: '케장콘 10', arg: '10' },
  { title: '제가 봤어요', subtitle: '케장콘 10', arg: '10' },
  { title: '다음부턴 그러지 마세요', subtitle: '케장콘 10', arg: '10' },
  { title: '예 미안합니다', subtitle: '케장콘 10', arg: '10' },
  { title: '맞는 말 같아서 수긍했다', subtitle: '케장콘 10', arg: '10' },
  { title: '진짜임', subtitle: '케장콘 10', arg: '10' },
  { title: '알겠습니까', subtitle: '케장콘 10', arg: '10' },
  { title: '(두려움에 떠는 오징어채)', subtitle: '케장콘 10', arg: '10' },
  { title: '유노', subtitle: '케장콘 10', arg: '10' },
  { title: '해보기도 전에 포기하지 마', subtitle: '케장콘 10', arg: '10' },
  { title: '해보기도 전에 도전하지 말라', subtitle: '케장콘 10', arg: '10' },
  { title: '그거 저희집에도 200개 정도 있을걸요', subtitle: '케장콘 10', arg: '10' },
  { title: '내가 그걸 어떻게 아냐', subtitle: '케장콘 10', arg: '10' },
  { title: '야 너 상태가 왜그랭', subtitle: '케장콘 10', arg: '10' },
  { title: '찐자루 좋와', subtitle: '케장콘 10', arg: '10' },
  { title: '받아 받 받아주겠니', subtitle: '케장콘 10', arg: '10' },
  { title: 'what', subtitle: '케장콘 10', arg: '10' },
  { title: '난 서양의 배추다', subtitle: '케장콘 11', arg: '11' },
  { title: '이것이 고관절 어떻게 된 일인지', subtitle: '케장콘 11', arg: '11' },
  { title: 'ㅇㅇ 알겠는걸 ㅋㅋ', subtitle: '케장콘 11', arg: '11' },
  { title: '대예의박', subtitle: '케장콘 11', arg: '11' },
  { title: '저가 하기 실어요', subtitle: '케장콘 11', arg: '11' },
  { title: '그것만은 알아둬라 좋아서 하는게 아님을', subtitle: '케장콘 11', arg: '11' },
  { title: '저이 이제 자요', subtitle: '케장콘 11', arg: '11' },
  { title: '자고 마는데', subtitle: '케장콘 11', arg: '11' },
  { title: '난 나를 믿어 미래의 내가 어떻게든 해줄거야', subtitle: '케장콘 11', arg: '11' },
  { title: '밥 먹고싶어 배 고파', subtitle: '케장콘 11', arg: '11' },
  { title: '술 마셨어요', subtitle: '케장콘 11', arg: '11' },
  { title: '근대니가 몰아냐고', subtitle: '케장콘 11', arg: '11' },
  { title: '어', subtitle: '케장콘 11', arg: '11' },
  { title: '와 와이라는교', subtitle: '케장콘 11', arg: '11' },
  { title: '(3D안경낀거)', subtitle: '케장콘 11', arg: '11' },
  { title: '고생하셨씀다 엉님', subtitle: '케장콘 11', arg: '11' },
  { title: 'O M G O 오이오이 M 믿고있었다고 G 젠장', subtitle: '케장콘 11', arg: '11' },
  { title: '유어웰컴 당신은 잘 오다', subtitle: '케장콘 11', arg: '11' },
  { title: '무시무시한 일이 아닐 수 없습니다', subtitle: '케장콘 11', arg: '11' },
  { title: 'v감탄v', subtitle: '케장콘 11', arg: '11' },
  { title: '금일 팩트 사용량을 초과하셨습니다', subtitle: '케장콘 11', arg: '11' },
  { title: '네알겟습니다', subtitle: '케장콘 11', arg: '11' },
  { title: '(땀 드랍하는거)', subtitle: '케장콘 11', arg: '11' },
  { title: '미안해 진심이 아니었어 사랑해', subtitle: '케장콘 11', arg: '11' },
  { title: '누구요', subtitle: '케장콘 12', arg: '12' },
  { title: '어떱혜알알냐', subtitle: '케장콘 12', arg: '12' },
  { title: '나때는 이런거 상상도 못했어 상상력부족', subtitle: '케장콘 12', arg: '12' },
  { title: '감사패 아무튼감사함', subtitle: '케장콘 12', arg: '12' },
  { title: '나는된다 나는된다', subtitle: '케장콘 12', arg: '12' },
  { title: '고운말써', subtitle: '케장콘 12', arg: '12' },
  { title: '하하 난 겁쟁이가 아니다', subtitle: '케장콘 12', arg: '12' },
  { title: '(물음표 띄우고 왔다갔다 하는거)', subtitle: '케장콘 12', arg: '12' },
  { title: '그재잉', subtitle: '케장콘 12', arg: '12' },
  { title: '않인가 않임말고', subtitle: '케장콘 12', arg: '12' },
  { title: '와아 와아아아 늦게까지 안잔 보람 有', subtitle: '케장콘 12', arg: '12' },
  { title: '칭찬해조 칭찬해조', subtitle: '케장콘 12', arg: '12' },
  { title: '(비디오 깨지듯 흔들리는 사람)', subtitle: '케장콘 12', arg: '12' },
  { title: '좋와요', subtitle: '케장콘 12', arg: '12' },
  { title: '공식적인 내생각', subtitle: '케장콘 12', arg: '12' },
  { title: '이달의 레전드 당신', subtitle: '케장콘 12', arg: '12' },
  { title: '아아 너무귀엽다', subtitle: '케장콘 12', arg: '12' },
  { title: '우우 나쁜사람', subtitle: '케장콘 12', arg: '12' },
  { title: '괜찮습니다 죄송하세요', subtitle: '케장콘 12', arg: '12' },
  { title: '경찰관님 여기에욧', subtitle: '케장콘 12', arg: '12' },
  { title: '너야말로 모지', subtitle: '케장콘 12', arg: '12' },
  { title: '하지만 이렇게 간단하게 피했습니다', subtitle: '케장콘 12', arg: '12' },
  { title: '아닛', subtitle: '케장콘 12', arg: '12' },
  { title: '(빛나는 별)', subtitle: '케장콘 12', arg: '12' },
  { title: '예 인정합니다 인정브래쓰 발사 푸슈', subtitle: '케장콘 13', arg: '13' },
  { title: '쾅 쾅', subtitle: '케장콘 13', arg: '13' },
  { title: '그게 저예요', subtitle: '케장콘 13', arg: '13' },
  { title: '울지마', subtitle: '케장콘 13', arg: '13' },
  { title: '히히', subtitle: '케장콘 13', arg: '13' },
  { title: '싼게 비지떡 싼 캐비지 떡', subtitle: '케장콘 13', arg: '13' },
  { title: '안녕못해 잘못지내 밥끊었어 번호바꼈어', subtitle: '케장콘 13', arg: '13' },
  { title: '난 커서 과학자가 될꺼야', subtitle: '케장콘 13', arg: '13' },
  { title: '그게 아니다 어리석은 녀석', subtitle: '케장콘 13', arg: '13' },
  { title: '당신은 서서히 잠에 듭니다 서서히', subtitle: '케장콘 13', arg: '13' },
  { title: '왠지 아세요', subtitle: '케장콘 13', arg: '13' },
  { title: '그렇게 잘 아는놈이 왜그런대', subtitle: '케장콘 13', arg: '13' },
  { title: '하아 고 리 타 분', subtitle: '케장콘 13', arg: '13' },
  { title: '너 그런애니 너 그런애였니', subtitle: '케장콘 13', arg: '13' },
  { title: '나만아니면돼', subtitle: '케장콘 13', arg: '13' },
  { title: '우리가 돈이없지 가오가 없냐', subtitle: '케장콘 13', arg: '13' },
  { title: '우리가 다없지 뭐가있냐', subtitle: '케장콘 13', arg: '13' },
  { title: '불꽃효도', subtitle: '케장콘 13', arg: '13' },
  { title: '인성 괜찮니', subtitle: '케장콘 13', arg: '13' },
  { title: '이었다고 한다', subtitle: '케장콘 13', arg: '13' },
  { title: '였던것', subtitle: '케장콘 13', arg: '13' },
  { title: '그래도 아직 할만한거같은데', subtitle: '케장콘 13', arg: '13' },
  { title: '안니', subtitle: '케장콘 13', arg: '13' },
  { title: '잘 하자 잘 해', subtitle: '케장콘 13', arg: '13' },
  { title: '이거 그만가져와', subtitle: '케장콘 14', arg: '14' },
  { title: '(그만가져오라는거 숙여서 피하는거)', subtitle: '케장콘 14', arg: '14' },
  { title: '아 이건 그 뭐더라', subtitle: '케장콘 14', arg: '14' },
  { title: '와 신난다', subtitle: '케장콘 14', arg: '14' },
  { title: '근대용(모던 타임즈 주래곤)', subtitle: '케장콘 14', arg: '14' },
  { title: '그럼다행이다', subtitle: '케장콘 14', arg: '14' },
  { title: '이게게임이냐', subtitle: '케장콘 14', arg: '14' },
  { title: '(상상도 못한 정체처럼 생긴거 ㄴㅇㄱ)', subtitle: '케장콘 14', arg: '14' },
  { title: '나도할래', subtitle: '케장콘 14', arg: '14' },
  { title: '하아 못해먹겟다', subtitle: '케장콘 14', arg: '14' },
  { title: '너의곁엔 우리가 있잖아', subtitle: '케장콘 14', arg: '14' },
  { title: '(금메달 걸고 V하는거)', subtitle: '케장콘 14', arg: '14' },
  { title: '재밌는 얘기 해주세요', subtitle: '케장콘 14', arg: '14' },
  { title: '? ㅋㅋ', subtitle: '케장콘 14', arg: '14' },
  { title: '얼씨구', subtitle: '케장콘 14', arg: '14' },
  { title: '(비오는 창문)', subtitle: '케장콘 14', arg: '14' },
  { title: '허허 난세로다', subtitle: '케장콘 14', arg: '14' },
  { title: '의심의 여지없는 조작 100% 가짜', subtitle: '케장콘 14', arg: '14' },
  { title: '난 모를란다', subtitle: '케장콘 14', arg: '14' },
  { title: '그럼 나도 모를란다 ㅋㅋ', subtitle: '케장콘 14', arg: '14' },
  { title: '루돌프', subtitle: '케장콘 14', arg: '14' },
  { title: '아니요ㅋ 아닌데요ㅋㅋ 어 아니야 ㅋㅋㅋ', subtitle: '케장콘 14', arg: '14' },
  { title: '님아 그렀타고 남한테 피에를 주면 않되재', subtitle: '케장콘 14', arg: '14' },
  { title: '네 아니 그래서 몬데이게 몬데이게다 이게다모냐고', subtitle: '케장콘 14', arg: '14' }
]
console.log(db[0].title.includes('말'))
